package com.example.onlineshop;

import android.os.Bundle;
import android.util.Log;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

import androidx.activity.EdgeToEdge;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;

import com.android.volley.Request;
import com.android.volley.RequestQueue;
import com.android.volley.toolbox.JsonObjectRequest;
import com.android.volley.toolbox.Volley;
import com.example.onlineshop.Models.Connection;
import com.example.onlineshop.Models.Product;
import com.google.gson.Gson;

import org.json.JSONException;
import org.json.JSONObject;

public class CreateProductActivity extends AppCompatActivity {

    private EditText editTextName, editTextDescription, editTextPrice, editTextImageUrl;
    private Button btnSave;
    private static final String API_URL = "http://" + Connection.getBaseUrl() + ":8080/products";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        EdgeToEdge.enable(this);
        setContentView(R.layout.activity_create_product);


        editTextName = findViewById(R.id.editText_Name);
        editTextDescription = findViewById(R.id.editText_Description);
        editTextPrice = findViewById(R.id.editText_Price);
        editTextImageUrl = findViewById(R.id.editText_ImageUrl);
        btnSave = findViewById(R.id.btn_Save);

        // Set the save button click listener
        btnSave.setOnClickListener(v -> createProduct());
    }

    private void createProduct() {
        // Get input values from the form
        String name = editTextName.getText().toString();
        String description = editTextDescription.getText().toString();
        String price = editTextPrice.getText().toString();
        String imageUrl = editTextImageUrl.getText().toString();

        // Validate fields
        if (name.isEmpty() || description.isEmpty() || price.isEmpty() || imageUrl.isEmpty()) {
            Toast.makeText(CreateProductActivity.this, "Please fill all fields", Toast.LENGTH_SHORT).show();
            return;
        }

        // Create a Product object using input values
        Product newProduct = new Product(0, name, description, Integer.parseInt(price), imageUrl); // Assuming ID is auto-generated by the API

        // Use Gson to convert the Product object into a JSON string
        Gson gson = new Gson();
        String productJson = gson.toJson(newProduct);

        try {
            // Create a JSON object from the string
            JSONObject jsonObject = new JSONObject(productJson);

            JsonObjectRequest postRequest = new JsonObjectRequest(
                    Request.Method.POST,
                    API_URL,
                    jsonObject,
                    response -> {
                        Toast.makeText(CreateProductActivity.this, "Product created successfully!", Toast.LENGTH_SHORT).show();
                        finish(); // Close activity after successful creation
                    },
                    error -> {
                        Log.e("CreateProduct", "Error creating product: " + error.toString());
                        Toast.makeText(CreateProductActivity.this, "Error creating product", Toast.LENGTH_SHORT).show();
                    }
            );

            RequestQueue requestQueue = Volley.newRequestQueue(this);
            requestQueue.add(postRequest);

        } catch (JSONException e) {
            e.printStackTrace();
            Toast.makeText(CreateProductActivity.this, "Error creating JSON data", Toast.LENGTH_SHORT).show();
        }
    }


}